version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
        - .:/usr/src/app:ro
    command: uvicorn main:app --host 0.0.0 --port 8000 --reload
    env_file:
      - ./.env
    restart: unless-stopped

  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - ./.env
    ports:
      - "3453:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

